### ISSUE TITLE
Any idea to set volume to wanted dB?

### ISSUE THREAD

**Issue by Trilis29** [machosallad/esphome-nad-uart#3]

**Comment by machosallad** [comment]
I guess it would be fully dependent on the amplifier/equipment in question you attempt to control. Have you got hold of the list of available commands in your case, or are you also attempting to control a NAD C356?

**Comment by Trilis29** [comment]
I have C388, I suppose should be the same as 356

**Comment by machosallad** [comment]
You need to verify the available commands for your model, if it has additional capabilites related to volume or not. Possible options are dependent on this.

**Comment by Trilis29** [comment]
volume should be possible with simple "=" operator.  Just need to implement in esphome that it reads on boot volume aswell and need maybe number entity for setting volume. through  - uart.write: "\rMain.Volume=\r"

**Comment by machosallad** [comment]
That is however not the case. The reference manual I have linked in README.md clearly states that the "=" operator is not supported [reference](https://www.yumpu.com/en/document/read/35405103/c356-rs232-command-list-nad-electronics-main-lektropacks).

![image](https://github.com/machosallad/esphome-nad-uart/assets/16154330/60b33790-580f-4b21-a27b-8eadaa1bef2d)

As it mentions, discrete values for the volume is not possible due to the motorised volume control. If you wish to set the volume to a predefined volume, you cannot rely on the amplifier for this handling. It has do be done in some other matter with custom code.

**Comment by Trilis29** [comment]
This is from C368/388 manual, seems it is possible. Would you consider to write aditional configuration for this? :) I think number component is needed and lambda to update volume from UART ?

![image](https://github.com/machosallad/esphome-nad-uart/assets/51697921/f18c5135-8f64-4e38-bcca-22b4085eec52)

**Comment by machosallad** [comment]
Then you're in luck! I have no intention to expand my configuration with unsupported commands for my model. I would advise you to create a fork of my repository and perform the required additions to the configuration file to get/set volume and create new lambdas & actions to control it.

**Comment by Trilis29** [comment]
Great I will try, you wouldn't mind helping me out if I am gonna be stuck? Has few solutions in mind tomorrow will try.

**Comment by Trilis29** [comment]
setting volume is possible, but maybe you know how I can convert string to float of Main.Volume=-24.5 for example? I need lambda to update volume number component so I could control volume from HA

**Comment by machosallad** [comment]
Assume you should be using atoi/atof or similar methods: https://cplusplus.com/reference/cstdlib/atof/

**Comment by Trilis29** [comment]
So I got volume working, also made a number slider which can be used with universal media player enitty to create media player in home assistant. But in home assistant need 2 helper entities: 
1. Convert dB to 0..1 scale for media_player volume_level
2. Convert 0..1 scale from volume_level slider in media_player again to -70dB and send to service number set to uppdate value.

Number component should have uart.write action aswell:

```
number:
  - platform: template
    name: "Current Volume"
    id: current_volume
    min_value: -70
    max_value: 0
    step: 0.5
    icon: "mdi:volume-high"
    set_action:
      then:
      - uart.write:
          id: uart_bus
          data: !lambda |-
              std::size_t pos;
              std::string str = "\rMain.Volume=" + std::to_string(x) + "\r";
              while ((pos = str.find("\\r")) != std::string::npos)
                str.replace(pos, 2, "\r");
              std::vector<uint8_t> vec(str.begin(), str.end());
              return vec; 

```
Also updated text_sensor so on_value lambda should update number component:

```
text_sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart_bus));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: "uart_readline"
    on_value:
      then:
      - lambda: |-
              std::string sensorState = id(uart_readline).state;
              if (sensorState.length() > 0) {
                size_t index = sensorState.find("Main.Volume=");
                if (index != std::string::npos) {
                  std::string floatValueStr = sensorState.substr(index + 12);
                  float floatValue = atof(floatValueStr.c_str());
                  id(current_volume).publish_state(floatValue);
                }
              }
```

Maybe everything could be done better way, still looking into. When will be finished I will make fork with full configuration for esphome and homeassistant to integrate with media_player, then would be possible to use fully with homekit, google home or assist to control anything :)
